import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildWordPressApplyPlan, type WordPressApplyPlan } from './apply-plan.ts';
import { executeWordPressApplyPlan } from './apply-executor.ts';
import { SupabaseRestDatabase, supabaseProjectRef } from './database.ts';
import { verifyExternalR2MediaStorage, verifyR2MediaStorage } from './r2-media.ts';
import type { MediaDownloadReport, WordPressManifest } from './types.ts';

interface CliOptions {
  manifest: string;
  r2Report: string;
  externalR2Report: string;
  mediaDownloadReport: string;
  mediaPublicOrigin: string;
  environment: 'development' | 'production' | null;
  outputDirectory: string | null;
  offline: boolean;
  apply: boolean;
  confirmProjectRef: string | null;
  confirmManifest: string | null;
  confirmPlan: string | null;
}

const USAGE = `Usage:
  pnpm import:wordpress -- \\
    --manifest /absolute/wordpress-manifest.json \\
    --media-download-report /absolute/media-download-report.json \\
    --r2-report /absolute/r2-media-dry-run-after.json \\
    --external-r2-report /absolute/external-media-r2-dry-run-final.json \\
    --environment development \\
    --media-public-origin https://development-media.example.com \\
    --offline
  pnpm import:wordpress -- [the same source and environment options]
  pnpm import:wordpress -- [the same source and environment options] --apply \\
    --confirm-project-ref PROJECT_REF \\
    --confirm-manifest MANIFEST_SHA256 \\
    --confirm-plan PLAN_SHA256

Modes:
  --offline                         Build a deterministic plan without network access
  default                           Read-only Supabase reconciliation dry run
  --apply                           Write the reviewed plan through Supabase REST

Required source and deployment options:
  --manifest /absolute/file.json    Manifest generated by import:wordpress:dry-run
  --media-download-report FILE      Complete download ledger used by the R2 report
  --r2-report FILE                  Direct R2 size and SHA-256 verification report
  --external-r2-report FILE         Verified external inline-image R2 mapping
  --environment VALUE               development or production
  --media-public-origin ORIGIN      HTTPS delivery origin used for cover/social URLs

Other options:
  --output-dir /absolute/path       Defaults to the manifest directory
  --confirm-project-ref VALUE       Required with --apply; must match SUPABASE_URL
  --confirm-manifest SHA256         Required with --apply; must match the manifest
  --confirm-plan SHA256             Required with --apply; must match the generated plan
  --help                            Show this help

Production rejects localhost, workers.dev, pages.dev, private IPv4, and the
mukhtalif-development hostname. A real production media delivery origin is mandatory.

Environment variables for database modes:
  SUPABASE_URL
  SUPABASE_SERVICE_ROLE_KEY
`;

function requireValue(args: string[], index: number, flag: string): string {
  const value = args[index + 1];
  if (!value || value.startsWith('--')) throw new Error(`${flag} requires a value`);
  return value;
}

function parseArgs(args: string[]): CliOptions | null {
  const options: CliOptions = {
    manifest: '',
    r2Report: '',
    externalR2Report: '',
    mediaDownloadReport: '',
    mediaPublicOrigin: '',
    environment: null,
    outputDirectory: null,
    offline: false,
    apply: false,
    confirmProjectRef: null,
    confirmManifest: null,
    confirmPlan: null,
  };
  for (let index = 0; index < args.length; index += 1) {
    const flag = args[index];
    if (flag === '--') continue;
    if (flag === '--help') return null;
    if (flag === '--offline') options.offline = true;
    else if (flag === '--apply') options.apply = true;
    else if (flag === '--manifest') options.manifest = requireValue(args, index++, flag);
    else if (flag === '--r2-report') options.r2Report = requireValue(args, index++, flag);
    else if (flag === '--external-r2-report') {
      options.externalR2Report = requireValue(args, index++, flag);
    } else if (flag === '--media-download-report') {
      options.mediaDownloadReport = requireValue(args, index++, flag);
    } else if (flag === '--media-public-origin') {
      options.mediaPublicOrigin = requireValue(args, index++, flag);
    } else if (flag === '--environment') {
      const environment = requireValue(args, index++, flag);
      if (environment !== 'development' && environment !== 'production') {
        throw new Error('--environment must be development or production');
      }
      options.environment = environment;
    } else if (flag === '--output-dir') {
      options.outputDirectory = requireValue(args, index++, flag);
    } else if (flag === '--confirm-project-ref') {
      options.confirmProjectRef = requireValue(args, index++, flag);
    } else if (flag === '--confirm-manifest') {
      options.confirmManifest = requireValue(args, index++, flag);
    } else if (flag === '--confirm-plan') {
      options.confirmPlan = requireValue(args, index++, flag);
    } else throw new Error(`Unknown option: ${flag}`);
  }
  if (!options.manifest) throw new Error('--manifest is required');
  if (!options.r2Report) throw new Error('--r2-report is required');
  if (!options.externalR2Report) throw new Error('--external-r2-report is required');
  if (!options.mediaDownloadReport) throw new Error('--media-download-report is required');
  if (!options.mediaPublicOrigin) throw new Error('--media-public-origin is required');
  if (!options.environment) throw new Error('--environment is required');
  if (options.offline && options.apply)
    throw new Error('--offline cannot be combined with --apply');
  return options;
}

async function atomicJson(filePath: string, value: unknown): Promise<void> {
  await mkdir(path.dirname(filePath), { recursive: true, mode: 0o700 });
  const temporary = `${filePath}.${process.pid}.tmp`;
  await writeFile(temporary, `${JSON.stringify(value, null, 2)}\n`, {
    encoding: 'utf8',
    mode: 0o600,
  });
  await rename(temporary, filePath);
}

function assertManifest(value: unknown): asserts value is WordPressManifest {
  if (!value || typeof value !== 'object') throw new Error('Manifest must be a JSON object');
  const candidate = value as Partial<WordPressManifest>;
  if (
    candidate.schemaVersion !== 1 ||
    !candidate.source ||
    !candidate.candidates ||
    typeof candidate.checksumSha256 !== 'string'
  ) {
    throw new Error('Manifest does not match WordPress schema version 1');
  }
}

function assertMediaDownloadReport(value: unknown): asserts value is MediaDownloadReport {
  if (!value || typeof value !== 'object') {
    throw new Error('Media download report must be a JSON object');
  }
  const candidate = value as Partial<MediaDownloadReport>;
  if (
    candidate.schemaVersion !== 1 ||
    !Number.isInteger(candidate.requested) ||
    !Number.isInteger(candidate.failed) ||
    !Array.isArray(candidate.results)
  ) {
    throw new Error('Media download report does not match schema version 1');
  }
}

function blockerCounts(plan: WordPressApplyPlan): Record<string, number> {
  const counts = new Map<string, number>();
  for (const report of plan.articleDependencies) {
    for (const reason of report.blockers) counts.set(reason, (counts.get(reason) ?? 0) + 1);
  }
  return Object.fromEntries([...counts].sort(([left], [right]) => left.localeCompare(right)));
}

function offlineReport(plan: WordPressApplyPlan): Record<string, unknown> {
  return {
    schemaVersion: 1,
    generatedAt: new Date().toISOString(),
    mode: 'offline',
    deploymentEnvironment: plan.mediaStorage.deploymentEnvironment,
    mediaPublicOrigin: plan.mediaStorage.mediaPublicOrigin,
    planChecksumSha256: plan.checksumSha256,
    manifestChecksumSha256: plan.source.manifest_checksum_sha256,
    counts: {
      people: plan.people.length,
      sourcePosts: plan.articleDependencies.length,
      readyArticles: plan.articles.length,
      blockedArticles: plan.blockedArticles.length,
      articleAuthors: plan.articleAuthors.length,
      books: plan.books.length,
      mediaAssets: plan.mediaAssets.length,
      pendingPages: plan.pendingPages.length,
      pendingMedia: plan.pendingMedia.length,
      externalInlineMedia: plan.externalInlineMedia.length,
      redirects: plan.redirects.length,
      excludedRedirects: plan.excludedRedirects.length,
    },
    blockerCounts: blockerCounts(plan),
    warnings: plan.warnings,
    errors: plan.errors,
  };
}

function requiredEnvironment(name: 'SUPABASE_URL' | 'SUPABASE_SERVICE_ROLE_KEY'): string {
  const value = process.env[name]?.trim();
  if (!value) throw new Error(`${name} is required for database modes`);
  return value;
}

function verifyApplyConfirmation(options: CliOptions, plan: WordPressApplyPlan, url: string): void {
  const projectRef = supabaseProjectRef(url);
  if (options.confirmProjectRef !== projectRef) {
    throw new Error('--confirm-project-ref does not match SUPABASE_URL');
  }
  if (options.confirmManifest !== plan.source.manifest_checksum_sha256) {
    throw new Error('--confirm-manifest does not match the reviewed manifest checksum');
  }
  if (options.confirmPlan !== plan.checksumSha256) {
    throw new Error('--confirm-plan does not match the generated plan checksum');
  }
}

async function main(): Promise<void> {
  const options = parseArgs(process.argv.slice(2));
  if (!options) {
    process.stdout.write(USAGE);
    return;
  }
  const manifestPath = path.resolve(options.manifest);
  const outputDirectory = path.resolve(options.outputDirectory ?? path.dirname(manifestPath));
  const mediaDownloadReportPath = path.resolve(options.mediaDownloadReport);
  const r2ReportPath = path.resolve(options.r2Report);
  const externalR2ReportPath = path.resolve(options.externalR2Report);
  const [manifestRaw, mediaDownloadReportRaw, r2ReportRaw, externalR2ReportRaw] = await Promise.all(
    [
      readFile(manifestPath, 'utf8'),
      readFile(mediaDownloadReportPath, 'utf8'),
      readFile(r2ReportPath, 'utf8'),
      readFile(externalR2ReportPath, 'utf8'),
    ],
  );
  const parsed = JSON.parse(manifestRaw) as unknown;
  const mediaDownloadReport = JSON.parse(mediaDownloadReportRaw) as unknown;
  const r2Report = JSON.parse(r2ReportRaw) as unknown;
  const externalR2Report = JSON.parse(externalR2ReportRaw) as unknown;
  assertManifest(parsed);
  assertMediaDownloadReport(mediaDownloadReport);
  const storage = verifyR2MediaStorage({
    manifest: parsed,
    mediaDownloadReport,
    mediaDownloadReportRaw,
    r2Report,
    r2ReportRaw,
    mediaPublicOrigin: options.mediaPublicOrigin,
    environment: options.environment!,
  });
  const externalStorage = verifyExternalR2MediaStorage({
    manifestRaw,
    r2Report: externalR2Report,
    r2ReportRaw: externalR2ReportRaw,
  });
  const plan = buildWordPressApplyPlan(parsed, storage, externalStorage);
  const planPath = path.join(outputDirectory, 'wordpress-apply-plan.json');
  const dependenciesPath = path.join(outputDirectory, 'wordpress-article-dependencies.json');
  const externalInlineMediaPath = path.join(
    outputDirectory,
    'wordpress-external-inline-media.json',
  );
  await atomicJson(planPath, plan);
  await atomicJson(dependenciesPath, {
    schemaVersion: 1,
    manifestChecksumSha256: plan.source.manifest_checksum_sha256,
    planChecksumSha256: plan.checksumSha256,
    articles: plan.articleDependencies,
  });
  await atomicJson(externalInlineMediaPath, {
    schemaVersion: 1,
    manifestChecksumSha256: plan.source.manifest_checksum_sha256,
    planChecksumSha256: plan.checksumSha256,
    count: plan.externalInlineMedia.length,
    dependencies: plan.externalInlineMedia,
  });

  if (options.offline) {
    const reportPath = path.join(outputDirectory, 'wordpress-apply-dry-run-report.json');
    const report = offlineReport(plan);
    await atomicJson(reportPath, report);
    process.stdout.write(
      `${JSON.stringify(
        { planPath, dependenciesPath, externalInlineMediaPath, reportPath, ...report },
        null,
        2,
      )}\n`,
    );
    return;
  }

  const supabaseUrl = requiredEnvironment('SUPABASE_URL');
  const serviceRoleKey = requiredEnvironment('SUPABASE_SERVICE_ROLE_KEY');
  if (options.apply) verifyApplyConfirmation(options, plan, supabaseUrl);
  const database = new SupabaseRestDatabase({ supabaseUrl, serviceRoleKey });
  const report = await executeWordPressApplyPlan({
    plan,
    database,
    apply: options.apply,
  });
  const reportPath = path.join(
    outputDirectory,
    options.apply ? 'wordpress-apply-report.json' : 'wordpress-apply-database-dry-run-report.json',
  );
  await atomicJson(reportPath, report);
  process.stdout.write(
    `${JSON.stringify(
      {
        planPath,
        dependenciesPath,
        externalInlineMediaPath,
        reportPath,
        projectRef: supabaseProjectRef(supabaseUrl),
        mode: report.mode,
        applied: report.applied,
        blocked: report.blocked,
        readyArticles: report.articles.planned,
        blockedArticles: report.blockedArticles.planned,
        plannedMutations: report.plannedMutations,
        errors: report.issues.filter((issue) => issue.level === 'error').length,
        warnings: report.issues.filter((issue) => issue.level === 'warning').length,
      },
      null,
      2,
    )}\n`,
  );
  if (report.blocked) process.exitCode = 2;
}

const invokedPath = process.argv[1] ? path.resolve(process.argv[1]) : '';
if (invokedPath === fileURLToPath(import.meta.url)) {
  main().catch((error: unknown) => {
    process.stderr.write(
      `${error instanceof Error ? (error.stack ?? error.message) : String(error)}\n`,
    );
    process.exitCode = 1;
  });
}
