import { DEFAULT_ROLE_PERMISSIONS } from '@mukhtalif/types';
import type { AdminStudioData, Article } from './models';

export const DEMO_AS_OF = '2026-08-09T12:00:00+03:00';

function createDemoArticle(
  article: Pick<
    Article,
    'id' | 'slug' | 'title' | 'author' | 'summary' | 'status' | 'createdAt' | 'updatedAt'
  > & {
    readonly publishedAt?: string;
    readonly newsletter?: Article['newsletter'];
  },
): Article {
  const content = {
    type: 'doc' as const,
    content: [
      {
        type: 'paragraph' as const,
        content: [{ type: 'text' as const, text: article.summary }],
      },
    ],
  };

  return {
    ...article,
    authorPlacement: 'after_title',
    excerpt: article.summary,
    content,
    contentHtml: `<p>${article.summary}</p>`,
    body: article.summary,
    seo: {
      title: article.title,
      description: article.summary,
      noIndex: article.status !== 'published',
    },
    newsletter: article.newsletter ?? {
      enabled: false,
      status: 'not_started',
      needsSync: false,
    },
    version: 1,
  };
}

const seed: AdminStudioData = {
  asOf: DEMO_AS_OF,
  homepageWeeklyEpisodesSettings: {
    enabled: true,
    title: 'حلقات آخر أسبوع من مختلف',
    windowDays: 7,
    version: 1,
    updatedAt: DEMO_AS_OF,
  },
  viewer: {
    id: 'studio_member_admin_badr',
    name: 'بدر القحطاني',
    email: 'admin@demo.mukhtalif.local',
    role: 'admin',
    roleName: 'المشرف العام',
    permissions: [...DEFAULT_ROLE_PERMISSIONS.admin],
    avatarInitial: 'ب',
  },
  plusPlan: {
    id: 'plan_plus_monthly',
    name: 'مختلف بلس',
    priceHalalas: 2900,
    currency: 'SAR',
    interval: 'month',
  },
  shows: [
    {
      id: 'show_batrooli',
      slug: 'batrooli',
      name: 'بترولي',
      host: 'أحمد العطار',
      category: 'الطاقة والنفط',
      premium: false,
      createdAt: '2023-02-12T10:00:00+03:00',
    },
    {
      id: 'show_ghilaf',
      slug: 'ghilaf',
      name: 'غلاف',
      host: 'محمد المرشدي',
      category: 'كتب وقراءة',
      premium: false,
      createdAt: '2023-10-08T10:00:00+03:00',
    },
    {
      id: 'show_shagla',
      slug: 'shagla',
      name: 'شقلة',
      host: 'عبدالله إسحاق',
      category: 'مجتمع ومنوعات',
      premium: false,
      createdAt: '2024-01-18T10:00:00+03:00',
    },
    {
      id: 'show_partition',
      slug: 'partition',
      name: 'بارتشن',
      host: 'أحمد حسن مشرف',
      category: 'بيئة العمل',
      premium: false,
      createdAt: '2024-04-11T10:00:00+03:00',
    },
    {
      id: 'show_sira',
      slug: 'sira',
      name: 'سيرة',
      host: 'فريق مختلف',
      category: 'سير ذاتية',
      premium: true,
      createdAt: '2024-09-01T10:00:00+03:00',
    },
  ],
  episodes: [
    {
      id: 'episode_9',
      title: 'طبيبة غيّرت مسارها إلى التقنية',
      showId: 'show_sira',
      episodeNumber: 7,
      durationMinutes: 55,
      status: 'draft',
      premium: true,
      notes: 'حوار مع ضيفة انتقلت من الطب إلى هندسة البرمجيات: الأسئلة النهائية قيد المراجعة.',
      createdAt: '2026-08-02T09:00:00+03:00',
      updatedAt: '2026-08-07T16:20:00+03:00',
    },
    {
      id: 'episode_10',
      title: 'السالفة مو سالفة راتب',
      showId: 'show_shagla',
      episodeNumber: 15,
      durationMinutes: null,
      status: 'draft',
      premium: false,
      notes: '',
      createdAt: '2026-08-03T11:00:00+03:00',
      updatedAt: '2026-08-05T14:45:00+03:00',
    },
    {
      id: 'episode_8',
      title: 'الهيدروجين الأخضر: وعد أم وهم؟',
      showId: 'show_batrooli',
      episodeNumber: 22,
      durationMinutes: 45,
      status: 'scheduled',
      premium: false,
      notes: '',
      audioFileName: 'batrooli-ep22-final.mp3',
      createdAt: '2026-07-27T09:00:00+03:00',
      updatedAt: '2026-08-08T18:15:00+03:00',
      scheduledAt: '2026-08-13T07:00:00+03:00',
    },
    {
      id: 'episode_7',
      title: 'كيف تقرأ سيرة ذاتية؟ الكتاب خلف التوظيف',
      showId: 'show_ghilaf',
      episodeNumber: 12,
      durationMinutes: 48,
      status: 'scheduled',
      premium: false,
      notes: '',
      audioFileName: 'ghilaf-ep12-final.mp3',
      createdAt: '2026-07-24T09:00:00+03:00',
      updatedAt: '2026-08-06T13:30:00+03:00',
      scheduledAt: '2026-08-20T09:00:00+03:00',
    },
    {
      id: 'episode_1',
      title: 'اجتماعات بلا نهاية: من يقتل الإنتاجية؟',
      showId: 'show_partition',
      episodeNumber: 8,
      durationMinutes: 29,
      status: 'published',
      premium: false,
      notes: '',
      audioFileName: 'partition-ep08-final.mp3',
      createdAt: '2026-07-20T10:00:00+03:00',
      updatedAt: '2026-07-30T08:00:00+03:00',
      publishedAt: '2026-07-30T08:00:00+03:00',
    },
    {
      id: 'episode_2',
      title: 'من التقاعد المبكر إلى تأسيس شركة',
      showId: 'show_sira',
      episodeNumber: 6,
      durationMinutes: 60,
      status: 'published',
      premium: true,
      notes: '',
      audioFileName: 'sira-ep06-final.mp3',
      createdAt: '2026-07-06T10:00:00+03:00',
      updatedAt: '2026-07-16T08:00:00+03:00',
      publishedAt: '2026-07-16T08:00:00+03:00',
    },
    {
      id: 'episode_3',
      title: 'ليش نمل من وظايفنا؟',
      showId: 'show_shagla',
      episodeNumber: 14,
      durationMinutes: 33,
      status: 'published',
      premium: false,
      notes: '',
      audioFileName: 'shagla-ep14-final.mp3',
      createdAt: '2026-06-29T10:00:00+03:00',
      updatedAt: '2026-07-09T08:00:00+03:00',
      publishedAt: '2026-07-09T08:00:00+03:00',
    },
    {
      id: 'episode_4',
      title: 'أسعار النفط: من يحرك السوق فعلًا؟',
      showId: 'show_batrooli',
      episodeNumber: 21,
      durationMinutes: 38,
      status: 'published',
      premium: false,
      notes: '',
      audioFileName: 'batrooli-ep21-final.mp3',
      createdAt: '2026-06-22T10:00:00+03:00',
      updatedAt: '2026-07-02T08:00:00+03:00',
      publishedAt: '2026-07-02T08:00:00+03:00',
    },
    {
      id: 'episode_5',
      title: 'العادات الذرية بين الترجمة والأصل',
      showId: 'show_ghilaf',
      episodeNumber: 11,
      durationMinutes: 51,
      status: 'published',
      premium: false,
      notes: '',
      audioFileName: 'ghilaf-ep11-final.mp3',
      createdAt: '2026-06-15T10:00:00+03:00',
      updatedAt: '2026-06-25T08:00:00+03:00',
      publishedAt: '2026-06-25T08:00:00+03:00',
    },
    {
      id: 'episode_6',
      title: 'من الحقل إلى الإدارة: رحلة مهندس',
      showId: 'show_batrooli',
      episodeNumber: 20,
      durationMinutes: 42,
      status: 'published',
      premium: false,
      notes: '',
      audioFileName: 'batrooli-ep20-final.mp3',
      createdAt: '2026-05-25T10:00:00+03:00',
      updatedAt: '2026-06-04T08:00:00+03:00',
      publishedAt: '2026-06-04T08:00:00+03:00',
    },
    {
      id: 'episode_11',
      title: 'الحلقة صفر: تجربة صوت',
      showId: 'show_partition',
      episodeNumber: 0,
      durationMinutes: 18,
      status: 'archived',
      premium: false,
      notes: '',
      audioFileName: 'partition-ep00-test.mp3',
      createdAt: '2026-05-01T10:00:00+03:00',
      updatedAt: '2026-05-12T12:00:00+03:00',
      archivedAt: '2026-05-12T12:00:00+03:00',
    },
  ],
  articles: [
    createDemoArticle({
      id: 'article_1',
      slug: 'guest-studio-guide',
      title: 'دليل الضيف: قبل أن تصل إلى الاستوديو',
      author: { type: 'custom', displayName: 'فريق مختلف' },
      summary: 'إرشادات عملية للضيف قبل التسجيل، من التحضير إلى الوصول وبدء الحوار.',
      status: 'draft',
      newsletter: {
        enabled: true,
        subject: 'قبل أن تصل إلى استوديو مختلف',
        preheader: 'دليل مختصر لتجربة تسجيل هادئة وواضحة.',
        status: 'draft',
        needsSync: false,
      },
      createdAt: '2026-08-04T10:00:00+03:00',
      updatedAt: '2026-08-08T15:30:00+03:00',
    }),
    createDemoArticle({
      id: 'article_2',
      slug: 'how-batrooli-is-recorded',
      title: 'خلف الكواليس: كيف تُسجَّل حلقة بترولي',
      author: { type: 'custom', displayName: 'أحمد العطار' },
      summary: 'رحلة الحلقة من اجتماع الإعداد حتى المراجعة الصوتية والنسخة النهائية.',
      status: 'draft',
      createdAt: '2026-07-29T10:00:00+03:00',
      updatedAt: '2026-08-03T12:15:00+03:00',
    }),
    createDemoArticle({
      id: 'article_3',
      slug: 'ghilaf-summer-reading-list',
      title: 'قائمة الصيف: ما يقرؤه فريق غلاف',
      author: { type: 'custom', displayName: 'محمد المرشدي' },
      summary: 'اختيارات فريق غلاف لقراءات الصيف، مع سبب قصير وراء كل ترشيح.',
      status: 'published',
      newsletter: {
        enabled: true,
        subject: 'قائمة الصيف من فريق غلاف',
        preheader: 'كتب اختارها الفريق مع سبب قصير وراء كل ترشيح.',
        status: 'sent',
        campaignId: 'fixture-weekly-20',
        syncedVersion: 1,
        needsSync: false,
        sentAt: '2026-07-20T09:15:00+03:00',
      },
      createdAt: '2026-07-12T10:00:00+03:00',
      updatedAt: '2026-07-20T08:00:00+03:00',
      publishedAt: '2026-07-20T08:00:00+03:00',
    }),
    createDemoArticle({
      id: 'article_4',
      slug: 'why-mukhtalif-plus',
      title: 'لماذا أطلقنا مختلف بلس؟',
      author: { type: 'custom', displayName: 'فريق مختلف' },
      summary: 'ما الذي يضيفه الاشتراك للمستمع، وكيف يدعم إنتاج حوارات أعمق.',
      status: 'published',
      createdAt: '2026-06-24T10:00:00+03:00',
      updatedAt: '2026-07-01T08:00:00+03:00',
      publishedAt: '2026-07-01T08:00:00+03:00',
    }),
  ],
  guests: [
    {
      id: 'guest_raed',
      slug: 'raed-al-shehri',
      name: 'رائد الشهري',
      role: 'مهندس مكامن · أرامكو السعودية',
      city: 'الظهران',
      email: 'raed@example.com',
      bio: 'مهندس مكامن أمضى أربعة عشر عامًا بين الحقل والإدارة، ويكتب عن اقتصاد الطاقة بلغة يفهمها غير المتخصص.',
      createdAt: '2025-05-18T10:00:00+03:00',
    },
    {
      id: 'guest_hessa',
      slug: 'hessa-al-mutairi',
      name: 'حصة المطيري',
      role: 'مترجمة وناشرة',
      city: 'الرياض',
      email: 'hessa@example.com',
      bio: 'ترجمت أكثر من عشرين كتابًا في علم النفس التطبيقي، وتدير دار نشر صغيرة تعنى بالكتب القصيرة.',
      createdAt: '2025-08-03T10:00:00+03:00',
    },
    {
      id: 'guest_majed',
      slug: 'majed-bin-sulaiman',
      name: 'ماجد بن سليمان',
      role: 'مدير منتج · شركة تقنية',
      city: 'جدة',
      email: 'majed@example.com',
      bio: 'عمل في ثلاث شركات ناشئة قبل أن يستقر في إدارة المنتجات، وله رأي حاد في ثقافة الاجتماعات.',
      createdAt: '2025-11-16T10:00:00+03:00',
    },
    {
      id: 'guest_lamia',
      slug: 'lamia-al-zahrani',
      name: 'لمياء الزهراني',
      role: 'طبيبة ومهندسة برمجيات',
      city: 'أبها',
      email: 'lamia@example.com',
      bio: 'تركت الممارسة السريرية بعد ست سنوات لتعمل في الصحة الرقمية، وتتحدث عن تكلفة تغيير المسار.',
      createdAt: '2026-01-09T10:00:00+03:00',
    },
    {
      id: 'guest_turki',
      slug: 'turki-al-enezi',
      name: 'تركي العنزي',
      role: 'مؤسس · متقاعد مبكرًا',
      city: 'الخبر',
      email: 'turki@example.com',
      bio: 'خرج من وظيفته الحكومية في التاسعة والثلاثين وأسّس شركة لوجستيات صغيرة، ويتحدث بصراحة عن الأرقام.',
      createdAt: '2026-02-22T10:00:00+03:00',
    },
    {
      id: 'guest_shaimaa',
      slug: 'shaimaa-bin-omar',
      name: 'شيماء بن عمر',
      role: 'باحثة اجتماعية',
      city: 'الدمام',
      email: 'shaimaa@example.com',
      bio: 'تدرس علاقة الشباب بسوق العمل، وتصل غالبًا بنتائج تخالف ما يتوقعه المستمع.',
      createdAt: '2026-03-14T10:00:00+03:00',
    },
  ],
  guestSocials: [
    { id: 'guest_social_raed_x', guestId: 'guest_raed', platform: 'x', handle: '@raed_eng' },
    {
      id: 'guest_social_raed_linkedin',
      guestId: 'guest_raed',
      platform: 'linkedin',
      handle: 'in/raedshehri',
    },
    { id: 'guest_social_hessa_x', guestId: 'guest_hessa', platform: 'x', handle: '@hessa_books' },
    {
      id: 'guest_social_hessa_instagram',
      guestId: 'guest_hessa',
      platform: 'instagram',
      handle: '@hessa.reads',
    },
    {
      id: 'guest_social_hessa_website',
      guestId: 'guest_hessa',
      platform: 'website',
      handle: 'hessa.sa',
    },
    {
      id: 'guest_social_majed_linkedin',
      guestId: 'guest_majed',
      platform: 'linkedin',
      handle: 'in/majedbs',
    },
    { id: 'guest_social_lamia_x', guestId: 'guest_lamia', platform: 'x', handle: '@lamia_dev' },
    {
      id: 'guest_social_lamia_linkedin',
      guestId: 'guest_lamia',
      platform: 'linkedin',
      handle: 'in/lamiaz',
    },
    { id: 'guest_social_turki_x', guestId: 'guest_turki', platform: 'x', handle: '@turki_v' },
    {
      id: 'guest_social_shaimaa_instagram',
      guestId: 'guest_shaimaa',
      platform: 'instagram',
      handle: '@shaimaa.research',
    },
    {
      id: 'guest_social_shaimaa_website',
      guestId: 'guest_shaimaa',
      platform: 'website',
      handle: 'shaimaa.org',
    },
  ],
  guestAppearances: [
    { guestId: 'guest_raed', episodeId: 'episode_4' },
    { guestId: 'guest_raed', episodeId: 'episode_6' },
    { guestId: 'guest_raed', episodeId: 'episode_8' },
    { guestId: 'guest_raed', episodeId: 'episode_1' },
    { guestId: 'guest_raed', episodeId: 'episode_3' },
    { guestId: 'guest_raed', episodeId: 'episode_11' },
    { guestId: 'guest_hessa', episodeId: 'episode_5' },
    { guestId: 'guest_majed', episodeId: 'episode_1' },
    { guestId: 'guest_majed', episodeId: 'episode_11' },
    { guestId: 'guest_lamia', episodeId: 'episode_9' },
    { guestId: 'guest_turki', episodeId: 'episode_2' },
    { guestId: 'guest_shaimaa', episodeId: 'episode_3' },
  ],
  studioMembers: [
    {
      id: 'studio_member_admin_badr',
      name: 'بدر القحطاني',
      email: 'admin@demo.mukhtalif.local',
      role: 'admin',
      roleName: 'المشرف العام',
      joinedAt: '2026-01-10T12:00:00+03:00',
    },
    {
      id: 'studio_member_editor_layan',
      name: 'ليان السبيعي',
      email: 'editor@demo.mukhtalif.local',
      role: 'editor',
      roleName: 'مدير المحتوى',
      joinedAt: '2026-02-18T12:00:00+03:00',
    },
  ],
  users: [
    {
      id: 'user_noura',
      name: 'نورة الشمري',
      email: 'listener@demo.mukhtalif.local',
      joinedAt: '2026-05-12T12:00:00+03:00',
    },
    {
      id: 'user_fahad',
      name: 'فهد الدوسري',
      email: 'fahad.dosari@outlook.com',
      joinedAt: '2026-06-03T12:00:00+03:00',
    },
    {
      id: 'user_sarah',
      name: 'سارة العتيبي',
      email: 'sarah.otaibi@gmail.com',
      joinedAt: '2026-06-21T12:00:00+03:00',
    },
    {
      id: 'user_khalid',
      name: 'خالد الغامدي',
      email: 'khalid.ghamdi@icloud.com',
      joinedAt: '2026-04-15T12:00:00+03:00',
    },
    {
      id: 'user_abdulrahman',
      name: 'عبدالرحمن الحربي',
      email: 'a.harbi@gmail.com',
      joinedAt: '2026-08-02T12:00:00+03:00',
    },
    {
      id: 'user_reem',
      name: 'ريم القحطاني',
      email: 'reem.qahtani@gmail.com',
      joinedAt: '2026-08-07T12:00:00+03:00',
    },
  ],
  subscriptions: [
    {
      id: 'subscription_noura',
      userId: 'user_noura',
      planId: 'plan_plus_monthly',
      status: 'active',
      priceHalalas: 2900,
      startedAt: '2026-06-12T12:00:00+03:00',
      updatedAt: '2026-08-09T12:00:00+03:00',
      renewAt: '2026-09-12T12:00:00+03:00',
    },
    {
      id: 'subscription_fahad',
      userId: 'user_fahad',
      planId: 'plan_plus_monthly',
      status: 'active',
      priceHalalas: 2900,
      startedAt: '2026-07-03T12:00:00+03:00',
      updatedAt: '2026-08-09T12:00:00+03:00',
      renewAt: '2026-09-03T12:00:00+03:00',
    },
    {
      id: 'subscription_sarah',
      userId: 'user_sarah',
      planId: 'plan_plus_monthly',
      status: 'past_due',
      priceHalalas: 2900,
      startedAt: '2026-06-21T12:00:00+03:00',
      updatedAt: '2026-07-21T12:00:00+03:00',
      paymentFailedAt: '2026-07-21T12:00:00+03:00',
    },
    {
      id: 'subscription_khalid',
      userId: 'user_khalid',
      planId: 'plan_plus_monthly',
      status: 'canceled',
      priceHalalas: 2900,
      startedAt: '2026-04-15T12:00:00+03:00',
      updatedAt: '2026-06-15T12:00:00+03:00',
      canceledAt: '2026-06-15T12:00:00+03:00',
    },
  ],
};

/** A ready-to-render snapshot. Use createDemoData when the caller will mutate local state. */
export const demoData: Readonly<AdminStudioData> = seed;

/** Returns a fresh, relation-preserving copy for each dashboard state container. */
export function createDemoData(): AdminStudioData {
  return {
    ...seed,
    homepageWeeklyEpisodesSettings: { ...seed.homepageWeeklyEpisodesSettings },
    viewer: { ...seed.viewer, permissions: [...seed.viewer.permissions] },
    plusPlan: { ...seed.plusPlan },
    shows: seed.shows.map((show) => ({ ...show })),
    episodes: seed.episodes.map((episode) => ({ ...episode })),
    articles: seed.articles.map((article) => ({ ...article })),
    guests: seed.guests.map((guest) => ({ ...guest })),
    guestSocials: seed.guestSocials.map((social) => ({ ...social })),
    guestAppearances: seed.guestAppearances.map((appearance) => ({ ...appearance })),
    studioMembers: seed.studioMembers.map((member) => ({ ...member })),
    users: seed.users.map((user) => ({ ...user })),
    subscriptions: seed.subscriptions.map((subscription) => ({ ...subscription })),
  };
}
