export { configureApi, setAuthToken, apiUrl, request, ApiError } from './client';
export type { ApiConfig } from './client';
export {
  showsService,
  episodesService,
  articlesService,
  plansService,
  subscriptionsService,
  meService,
  usersService,
  followsService,
  progressService,
} from './services';
export type { EpisodeFilter, ArticleFilter } from './services';
export {
  useShows,
  useShow,
  useCreateShow,
  useUpdateShow,
  useEpisodes,
  useEpisode,
  useCreateEpisode,
  useUpdateEpisode,
  useUpdateEpisodeStatus,
  useArticles,
  useArticle,
  useCreateArticle,
  useUpdateArticle,
  useUpdateArticleStatus,
  usePlans,
  useSubscriptions,
  useCreateSubscription,
  useUpdateSubscriptionStatus,
  useMe,
  useMySubscription,
  useUsers,
  useFollows,
  useFollow,
  useUnfollow,
  useProgress,
  useUpsertProgress,
} from './hooks';
